import { Paciente, Usuario, Turno, Receta, Evolucion, Clinica } from './types';

export const INITIAL_CLINICAS: Clinica[] = [
  {
    id: 'c1',
    nombre: 'MediCare Central - Centro Médico',
    cuit: '30-71234567-9',
    direccion: 'Av. Santa Fe 2450, CABA',
    telefono: '+54 11 4821-9000',
    email: 'contacto@medicare-central.com',
  },
  {
    id: 'c2',
    nombre: 'MediCare Norte - Sede Olivos',
    cuit: '30-71234568-7',
    direccion: 'Av. del Libertador 3200, Olivos',
    telefono: '+54 11 4799-5500',
    email: 'olivos@medicare-central.com',
  }
];

export const INITIAL_USUARIOS: Usuario[] = [
  {
    id: 'u1',
    usuarioLogin: 'admin',
    nombre: 'Dr. Alejandro Martinez',
    email: 'admin@medicare.pro',
    rol: 'SuperAdmin',
    matricula: 'MN 114820',
    empresa: 'MediCare Central - Centro Médico',
    perfilProfesional: 'Director Médico',
    estado: 'Activo',
  },
  {
    id: 'u2',
    usuarioLogin: 'medico1',
    nombre: 'Dra. Sofía Rossi',
    email: 'srossi@medicare.pro',
    rol: 'Medico',
    matricula: 'MN 138402',
    empresa: 'MediCare Central - Centro Médico',
    perfilProfesional: 'Cardiología',
    estado: 'Activo',
  },
  {
    id: 'u3',
    usuarioLogin: 'enfermeria1',
    nombre: 'Lic. Carlos Benítez',
    email: 'cbenitez@medicare.pro',
    rol: 'Enfermeria',
    matricula: 'MN 84521',
    empresa: 'MediCare Central - Centro Médico',
    perfilProfesional: 'Enfermería General / Terapia',
    estado: 'Activo',
  },
  {
    id: 'u4',
    usuarioLogin: 'recepcion',
    nombre: 'Mariana Gomez',
    email: 'mgomez@medicare.pro',
    rol: 'Operativo',
    empresa: 'MediCare Central - Centro Médico',
    perfilProfesional: 'Recepción y Admisiones',
    estado: 'Activo',
  }
];

export const INITIAL_PACIENTES: Paciente[] = [
  {
    id: 'p1',
    dni: '28456123',
    nombre: 'Juan Carlos',
    apellido: 'Fernández',
    fechaNacimiento: '1981-04-12',
    edad: 45,
    sexo: 'M',
    obraSocial: 'OSDE 310',
    numeroAfiliado: '84729103-01',
    telefono: '+54 9 11 5823-9941',
    email: 'jcfernandez@gmail.com',
    direccion: 'Av. Corrientes 3420 4to B, CABA',
    alergias: 'Penicilina (moderada), Ibuprofeno',
    antecedentes: 'Hipertensión arterial primaria, Dislipidemia',
    diagnosticoPrincipal: 'HTA controlada / Chequeo cardiológico',
    estado: 'Activo',
    clinica: 'MediCare Central - Centro Médico',
    creadoEn: '2026-01-15T10:30:00Z',
    ultimaVisita: '2026-09-24T15:20:00Z',
  },
  {
    id: 'p2',
    dni: '34982104',
    nombre: 'María Elena',
    apellido: 'García Moreno',
    fechaNacimiento: '1989-11-23',
    edad: 36,
    sexo: 'F',
    obraSocial: 'Swiss Medical',
    numeroAfiliado: '90123841-02',
    telefono: '+54 9 11 6721-3310',
    email: 'm.garcia@outlook.com',
    direccion: 'Juramento 2150 8vo A, Belgrano, CABA',
    alergias: 'Ninguna conocida',
    antecedentes: 'Asma bronquial intermitente',
    diagnosticoPrincipal: 'Control neumonológico semestral',
    estado: 'Activo',
    clinica: 'MediCare Central - Centro Médico',
    creadoEn: '2026-02-10T14:15:00Z',
    ultimaVisita: '2026-09-25T11:00:00Z',
  },
  {
    id: 'p3',
    dni: '14238910',
    nombre: 'Roberto',
    apellido: 'Alvarez',
    fechaNacimiento: '1958-08-05',
    edad: 68,
    sexo: 'M',
    obraSocial: 'PAMI / Plan Médico',
    numeroAfiliado: '14002391034',
    telefono: '+54 9 11 4410-9821',
    direccion: 'Maipú 840, San Isidro',
    alergias: 'Sulfas',
    antecedentes: 'Diabetes Mellitus Tipo 2, Insuficiencia Venosa',
    diagnosticoPrincipal: 'Control glucémico y curación de herida MMII',
    estado: 'Internado',
    clinica: 'MediCare Central - Centro Médico',
    creadoEn: '2025-11-20T08:00:00Z',
    ultimaVisita: '2026-09-26T08:30:00Z',
  },
  {
    id: 'p4',
    dni: '42109482',
    nombre: 'Lucas',
    apellido: 'Santillán',
    fechaNacimiento: '2000-02-18',
    edad: 26,
    sexo: 'M',
    obraSocial: 'Galeno 220',
    numeroAfiliado: '7721839-01',
    telefono: '+54 9 11 3320-1194',
    email: 'lucas.santillan@live.com',
    direccion: 'Thames 1420, Palermo, CABA',
    alergias: 'Ninguna',
    antecedentes: 'Apendicectomía (2018)',
    diagnosticoPrincipal: 'Apto físico deportivo',
    estado: 'Ambulatorio',
    clinica: 'MediCare Central - Centro Médico',
    creadoEn: '2026-09-01T09:00:00Z',
    ultimaVisita: '2026-09-22T16:00:00Z',
  }
];

export const INITIAL_EVOLUCIONES: Evolucion[] = [
  {
    id: 'e1',
    pacienteId: 'p1',
    fechaHora: '2026-09-24T15:20:00Z',
    profesionalNombre: 'Dra. Sofía Rossi',
    profesionalRol: 'Médica Cardióloga',
    matricula: 'MN 138402',
    tipoNota: 'Evolución Médica',
    evolucionClinica: 'Paciente concurre a control programado de TA. Refiere buena tolerancia a la medicación sin cefaleas ni edemas. ECG en ritmo sinusal sin alteraciones agudas.',
    indicaciones: 'Continuar con Enalapril 10mg cada 12hs. Dieta hiposódica y actividad física regular. Próximo control con laboratorio en 6 meses.',
    signosVitales: {
      presionArterial: '125/80',
      frecuenciaCardiaca: 72,
      frecuenciaRespiratoria: 16,
      temperatura: 36.4,
      saturacionOxigeno: 98,
      glucemia: 94,
      peso: 82.5,
      fechaHora: '2026-09-24T15:15:00Z',
      profesional: 'Dra. Sofía Rossi',
    }
  },
  {
    id: 'e2',
    pacienteId: 'p3',
    fechaHora: '2026-09-26T08:30:00Z',
    profesionalNombre: 'Lic. Carlos Benítez',
    profesionalRol: 'Enfermero',
    matricula: 'MN 84521',
    tipoNota: 'Control Enfermería',
    evolucionClinica: 'Se realiza curación plana de úlcera en miembro inferior izquierdo. Se observa tejido de granulación limpio, sin secreción purulenta ni signos de infección activa.',
    indicaciones: 'Aplicar apósito hidrocoloide. Curación cada 48 horas. Control de glucemias preprandiales.',
    signosVitales: {
      presionArterial: '130/85',
      frecuenciaCardiaca: 78,
      frecuenciaRespiratoria: 18,
      temperatura: 36.7,
      saturacionOxigeno: 97,
      glucemia: 142,
      fechaHora: '2026-09-26T08:25:00Z',
      profesional: 'Lic. Carlos Benítez',
    }
  }
];

export const INITIAL_TURNOS: Turno[] = [
  {
    id: 't1',
    pacienteId: 'p1',
    pacienteNombre: 'Juan Carlos Fernández',
    pacienteDni: '28456123',
    profesionalId: 'u2',
    profesionalNombre: 'Dra. Sofía Rossi',
    especialidad: 'Cardiología',
    fecha: '2026-09-26',
    hora: '10:30',
    estado: 'En Sala de Espera',
    motivo: 'Control de hipertensión y holter',
    tipo: 'Consultorio',
    clinica: 'MediCare Central - Centro Médico',
  },
  {
    id: 't2',
    pacienteId: 'p2',
    pacienteNombre: 'María Elena García Moreno',
    pacienteDni: '34982104',
    profesionalId: 'u1',
    profesionalNombre: 'Dr. Alejandro Martinez',
    especialidad: 'Clínica Médica',
    fecha: '2026-09-26',
    hora: '11:15',
    estado: 'Confirmado',
    motivo: 'Evaluación de espirometría y tratamiento',
    tipo: 'Consultorio',
    clinica: 'MediCare Central - Centro Médico',
  },
  {
    id: 't3',
    pacienteId: 'p4',
    pacienteNombre: 'Lucas Santillán',
    pacienteDni: '42109482',
    profesionalId: 'u2',
    profesionalNombre: 'Dra. Sofía Rossi',
    especialidad: 'Cardiología',
    fecha: '2026-09-26',
    hora: '12:00',
    estado: 'Pendiente',
    motivo: 'Ergometría de 12 derivaciones',
    tipo: 'Consultorio',
    clinica: 'MediCare Central - Centro Médico',
  },
  {
    id: 't4',
    pacienteId: 'p3',
    pacienteNombre: 'Roberto Alvarez',
    pacienteDni: '14238910',
    profesionalId: 'u3',
    profesionalNombre: 'Lic. Carlos Benítez',
    especialidad: 'Enfermería Domiciliaria',
    fecha: '2026-09-26',
    hora: '14:30',
    estado: 'Confirmado',
    motivo: 'Curación domiciliaria y control vitales',
    tipo: 'Domicilio',
    clinica: 'MediCare Central - Centro Médico',
  }
];

export const INITIAL_RECETAS: Receta[] = [
  {
    id: 'r1',
    pacienteId: 'p1',
    pacienteNombre: 'Juan Carlos Fernández',
    pacienteDni: '28456123',
    fecha: '2026-09-24',
    profesionalNombre: 'Dra. Sofía Rossi',
    matricula: 'MN 138402',
    diagnostico: 'I10 - Hipertensión esencial primaria',
    estado: 'Activa',
    observaciones: 'Tratamiento crónico - Válido por 30 días',
    medicamentos: [
      {
        id: 'm1',
        nombreComercial: 'Lotrial 10mg',
        principioActivo: 'Enalapril',
        presentacion: 'Caja x 60 comprimidos',
        dosis: '1 comprimido (10mg)',
        frecuencia: 'Cada 12 horas',
        duracion: '60 días',
        indicaciones: 'Tomar por la mañana y noche con abundante agua.'
      },
      {
        id: 'm2',
        nombreComercial: 'Rosuvastatina 10mg',
        principioActivo: 'Rosuvastatina Cálcica',
        presentacion: 'Caja x 30 comprimidos',
        dosis: '1 comprimido (10mg)',
        frecuencia: 'Cada 24 horas',
        duracion: '30 días',
        indicaciones: 'Tomar por la noche luego de la cena.'
      }
    ]
  }
];
